apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zfy2k7x0s-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zfy2k7x0s-java-springboot-gitops